target-version = "py310"
line-length = 120

[lint]
select = [
    "E",    # pycodestyle errors: Checks against PEP 8 errors
    "F",    # pyflakes
    "I",    # isort: import sorting
    "S",    # flake8-bandit: security checks from Bandit
    "B",    # flake8-bugbear: finds likely bugs and design problems in your program
    "PT",   # flake8-pytest-style: pytest style checks
    # "ANN",  # flake8-annotations: checks for missing type annotations
    "DTZ",  # flake8-datetimez: checks for correct datetime usage
    "ISC",  # flake8-implicit-str-concat: checks for implicitly concatenated strings in a list
    "RET",  # flake8-return: checks return values
    "PTH",  # flake8-use-pathlib: encourages the use of pathlib over os.path
    "N",    # pep8-naming: Naming convention checks
    "UP",   # pyupgrade: checks for older syntax versions and suggests upgrades
    "NPY",  # numpy-specific rules
    "PD",   # pandas-vet: Checks for pandas best practices and potential errors
]

unfixable = [
    "B",
]

ignore = [
  "ANN101", # ignoring 'self' type annotation rule
  "ANN102", # ignoring 'cls' type annotation rule
  "ISC001", # ruff recommends disabling the rule
]

[lint.per-file-ignores]
"tests/*" = [
  "S101", # Security check: assert statements
  "S311", # Security check: random
]